In [2]:
import numpy as np
a=np.array([0,1.5,2])
print(a)

[0.  1.5 2. ]


In [7]:
import numpy as np
a=np.arange(20)
print(a)
b=np.arange(1,21)
print(b)
e = np.zeros(5)
print(e)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[0. 0. 0. 0. 0.]


In [10]:
a = np.arange(1, 101).reshape(10, 10)
print(a)
print(a[1:3,1:3])

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[12 13]
 [22 23]]


In [14]:
a =  [[0, 0, 0], [0, 0, 0], [0, 0, 0]]
b = [1, 1, 1]
print(a)
c = np.insert(a, 2, b, 0)
print(c)
e = np.insert(a, 2, b, 1)
print(e)


[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[0 0 0]
 [0 0 0]
 [1 1 1]
 [0 0 0]]
[[0 0 1 0]
 [0 0 1 0]
 [0 0 1 0]]


In [18]:
a = np.arange(1, 7).reshape(2, 3)
b = np.arange(7, 13).reshape(2, 3)
print(a)
print(b)
print(b + a)
print(b - a)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]
[[6 6 6]
 [6 6 6]]
